version: '3'

services:
  # Server di discovery
  discovery:
    build:
      context: .
      dockerfile: docker/Dockerfile.discovery
    ports:
      - "8000:8000/udp"
    environment:
      - BIND=0.0.0.0
      - PORT=8000
    restart: unless-stopped
    networks:
      - meshnet

  # Web UI (opzionale)
  webui:
    build:
      context: .
      dockerfile: docker/Dockerfile.webui
    ports:
      - "8080:8080"
    environment:
      - DISCOVERY_HOST=discovery
      - DISCOVERY_PORT=8000
    depends_on:
      - discovery
    restart: unless-stopped
    networks:
      - meshnet

networks:
  meshnet:
    driver: bridge 